<h1><?=lang('pvc_page_title')?></h1>
<h5><?=lang('pvc_text1')?></h5>
<p><?=lang('pvc_text2')?></p>
<p><?=lang('pvc_text3')?></p>
<p><?=lang('pvc_text4')?></p>
<p>- <?=lang('pvc_text5')?></p>
<p>- <?=lang('pvc_text6')?></p>
<p>- <?=lang('pvc_text7')?></p>
<p><?=lang('pvc_text8')?></p>
<p><?=lang('pvc_text9')?></p>
<p>- <?=lang('pvc_text10')?></p>
<p>- <?=lang('pvc_text11')?></p>
<p>- <?=lang('pvc_text12')?></p>
<p>- <?=lang('pvc_text13')?></p>
<p><?=lang('pvc_text14')?></p>
<p><?=lang('pvc_text15')?></p>
<p><?=lang('pvc_text16')?></p>
<p><?=lang('pvc_text17')?></p>
<p><?=lang('pvc_text18')?></p>
<p><?=lang('pvc_text19')?></p>